### ISSUE TITLE
stop at loading: 99%

### ISSUE THREAD

**Issue by Raphael233** [Lingluoluo/arknights#1]
I cloned it to my own server, with nodejs12, execute "serve", with an error:

ERROR: Cannot copy to clipboard: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Inappropriate ioctl for device

but serving successfully.
But when I open the page in chrome, it stopping at "load: 100%".

Thanks for sharing and what's the problem with me?

**Comment by Lingluoluo** [comment]
i have updated the code.Please cloned it and try again.There are a lot of problems in the last version that haven't been fixed.
